name = "dag"
version = "1.0.0"
license = "BSD"
author = ["Damian Rouson", "Robert Singleterry", "Brad Richardson"]
maintainer = "damian@sourceryinstitute.org"
copyright = "2020 Sourcery Institute"

[dependencies]
jsonff = {git = "https://gitlab.com/everythingfunctional/jsonff", tag = "v2.1.0"}
erloff = {git = "https://gitlab.com/everythingfunctional/erloff", tag = "v2.0.0"}
iso_varying_string = {git = "https://gitlab.com/everythingfunctional/iso_varying_string", tag = "v2.0.0"}
sourcery = {git = "https://github.com/sourceryinstitute/sourcery", tag = "1.0.0"}

[dev-dependencies]
vegetables = {git = "https://gitlab.com/everythingfunctional/vegetables", tag = "v7.0.2"}

[[test]]
name="jacobExample"
source-dir="tests/integration/jacob-example"
main="test-jacob-example.f90"

[[test]]
name="multipleIndependents"
source-dir="tests/integration/multiple-independents"
main="test-multiple-independents.f90"

[[test]]
name="inputOutput"
source-dir="tests/unit/input-output"
main="main.f90"
