add_edge – daglib
add_edge Subroutine
14 statements
Source File
private subroutine add_edge(me, e, label, attributes)
add an edge index for this vertex
Type Bound
vertex
Arguments
Type Intent Optional Attributes Name
class(vertex), intent(inout) :: me
integer(kind=ip), intent(in) :: e
character(len=*), intent(in), optional :: label
character(len=*), intent(in), optional :: attributes
other attributes when saving as a diagraph.
Calls
Called by
Source Code
    subroutine add_edge(me,e,label,attributes)
    class(vertex),intent(inout) :: me
    integer(ip),intent(in) :: e
    character(len=*),intent(in),optional :: label
    character(len=*),intent(in),optional :: attributes !! other attributes when
                                                       !! saving as a diagraph.
    if (allocated(me%edges)) then
        if (.not. any(e==me%edges%ivertex)) then ! don't add if already there
            me%edges = [me%edges, edge(e,label=label,attributes=attributes)]
            call sort_ascending(me%edges)
        end if
    else
        me%edges = [edge(e,label=label,attributes=attributes)]
    end if
    end subroutine add_edge
Call graph
add_edge calls sort_ascending
sort_ascending calls swap
set_edge_vector_vector calls add_edge
dag_set_edges_no_atts calls set_edges
dag_set_edges_vector_atts calls set_edges