dag_add_edge – daglib
dag_add_edge Subroutine
9 statements
Source File
private subroutine dag_add_edge(me, ivertex, iedge, label, attributes, metadata)
Add an edge to a dag.
Type Bound
dag
Arguments
Type Intent Optional Attributes Name
class(dag), intent(inout) :: me
integer(kind=ip), intent(in) :: ivertex
vertex number
integer(kind=ip), intent(in) :: iedge
the vertex to connect to ivertex
character(len=*), intent(in), optional :: label
edge label
character(len=*), intent(in), optional :: attributes
other attributes when saving as a diagraph.
class(*), intent(in), optional :: metadata
optional user-defined metadata
Calls
Source Code
    subroutine dag_add_edge(me,ivertex,iedge,label,attributes,metadata)
    class(dag),intent(inout) :: me
    integer(ip),intent(in)   :: ivertex !! vertex number
    integer(ip),intent(in)   :: iedge   !! the vertex to connect to `ivertex`
    character(len=*),intent(in),optional :: label !! edge label
    character(len=*),intent(in),optional :: attributes !! other attributes when
                                                       !! saving as a diagraph.
    class(*),intent(in),optional :: metadata !! optional user-defined metadata
    call me%vertices(ivertex)%set_edges(iedge,&
                        label=label,&
                        attributes=attributes,&
                        metadata=metadata)
    end subroutine dag_add_edge
Call graph
dag_add_edge calls set_edges
add_edge calls sort_ascending
set_edge_vector_vector calls sort_ascending
sort_ascending calls swap