set_edge_vector_vector – daglib
set_edge_vector_vector Subroutine
18 statements
Source File
private subroutine set_edge_vector_vector(me, edges, label, attributes)
specify the edge indices for this vertex
Type Bound
vertex
Arguments
Type Intent Optional Attributes Name
class(vertex), intent(inout) :: me
integer(kind=ip), intent(in), dimension(:) :: edges
character(len=*), intent(in), optional, dimension(:) :: label
character(len=*), intent(in), optional, dimension(:) :: attributes
other attributes when saving as a diagraph.
Calls
Called by
Source Code
    subroutine set_edge_vector_vector(me,edges,label,attributes)
    class(vertex),intent(inout) :: me
    integer(ip),dimension(:),intent(in) :: edges
    character(len=*),dimension(:),intent(in),optional :: label
    character(len=*),dimension(:),intent(in),optional :: attributes !! other attributes when
                                                                    !! saving as a diagraph.
    integer(ip) :: i !! counter
    do i=1,size(edges)
        if (present(label) .and. present(attributes)) then
            call me%add_edge(edges(i),label=label(i),attributes=attributes(i))
        else if (.not. present(label) .and. present(attributes)) then
            call me%add_edge(edges(i),attributes=attributes(i))
        else if (present(label) .and. .not. present(attributes)) then
            call me%add_edge(edges(i),label=label(i))
        else
            call me%add_edge(edges(i))
        end if
    end do
    end subroutine set_edge_vector_vector
Call graph
set_edge_vector_vector calls add_edge
add_edge calls sort_ascending
sort_ascending calls swap
dag_set_edges_no_atts calls set_edges
dag_set_edges_vector_atts calls set_edges