swap – daglib
swap Subroutine
8 statements
Source File
private impure elemental subroutine swap(i1, i2)
Swap two edge values.
Arguments
Type Intent Optional Attributes Name
type(edge), intent(inout) :: i1
type(edge), intent(inout) :: i2
Called by
Source Code
    impure elemental subroutine swap(i1,i2)
    type(edge),intent(inout) :: i1
    type(edge),intent(inout) :: i2
    type(edge) :: tmp
    tmp = i1
    i1  = i2
    i2  = tmp
    end subroutine swap
Call graph
sort_ascending calls swap
add_edge calls sort_ascending
set_edge_vector_vector calls sort_ascending
unique calls sort_ascending
dag_add_edge calls set_edges
dag_set_edges_no_atts calls set_edges
dag_set_edges_vector_atts calls set_edges