name: CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.0
      with:
        format: 'YYYY-MM'

    - name: Setup cache for opencoarrays
      id: cache-opencoarrays
      uses: actions/cache@v2
      with:
        path: "OpenCoarrays-2.9.2/"
        key: ${{ steps.time.outputs.time }}

    - name: Install GFortran, OpenCoarrays,and fpm
      run: |
        sudo apt install -y gfortran-10 graphviz
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-10 \
        --slave /usr/bingcov gcov /usr/bin/gcov-10
        if [ ! -d OpenCoarrays-2.9.2 ] ; then wget -P . https://github.com/sourceryinstitute/OpenCoarrays/releases/download/2.9.2/OpenCoarrays-2.9.2.tar.gz && tar -xf OpenCoarrays-2.9.2.tar.gz && cd OpenCoarrays-2.9.2 && TERM=xterm ./install.sh -y; fi
        wget https://github.com/fortran-lang/fpm/releases/download/v0.1.3/fpm-0.1.3-linux-x86_64 && sudo cp fpm-0.1.3-linux-x86_64 /usr/local/bin/fpm && chmod a+x /usr/local/bin/fpm

    - name: Build and test
      run: |
        source OpenCoarrays-2.9.2/prerequisites/installations/opencoarrays/2.9.2/setup.sh
        fpm test --compiler caf --runner "cafrun -n 1"
